services:
  - type: web
    name: borg    # Replace "borg" with your Render service name if different
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    nodeVersion: 18
